name: blank

on:
  push:

jobs:
  cue:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        block: ["determine", "clue", "particle", "ancestor", "meaning"]
        canteen: ["molecule", "complicated", "goods", "comprehensive"]
    steps:
    - uses: actions/checkout@v6
    - uses: actions/setup-java@v5
      with:
        distribution: 'zulu'
        java-version: '25'
    - run: java -jar OA
